[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.install]
cmds = ["rm -f package-lock.json", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "sh -c 'npx vite preview --host 0.0.0.0 --port ${PORT:-3000}'"
